version: "3.8"
services:
  mysqlservice:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_ROOT_PASSWORD=cxvxc2389vcxzv234r
    ports:
      - '3306:3306'
  app:
    container_name: migrations-app
    build:
      context: ./
    image: migrations-app
    depends_on:
      - mysqlservice
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://root:cxvxc2389vcxzv234r@mysqlservice:3306/mysqldb
    links:
      - mysqlservice