version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_ROOT_PASSWORD=cxvxc2389vcxzv234r
      - MYSQL_USER=mysqladmin
      - MYSQL_PASSWORD=p4ssw0rd
    ports:
      - '3306:3306'
  app:
    container_name: migrations-app
    build:
      context: ./
      target: production
    image: migrations-app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://mysqladmin:p4ssw0rd@localhost:3306/mysqldb
    links:
      - db
